= Monitor Network Usage
:toc:
:sectnums:
:sectnumlevels: 4

Monitor current network usage.


== Usage
Run `networkUsageProc.py` and network usage monitoring is started.

Data is stored in json file (currently to `./logs/networkUsage.json` - relative
to `networkUsageProc.py` location)

[source,json]
----
[
  {"name": "enp3s0", "bypsRx": 0, "bypsTx": 0},
  {"name": "wlp4s0", "bypsRx": 51152, "bypsTx": 3183824},
  {"name": "total", "bypsRx": 51152, "bypsTx": 3183824}
]
----

Interfaces monitored are all that match this parameters:

- `wl*`
- `enp*`
- `eth?:`


== Requirements
* https://www.gnu.org/software/make/[GNU - make]
* https://pypi.org/project/mccabe/[pip - mccabe]
* https://pypi.org/project/flake8/[pip - flake8]

For `pip` packages you can call `make setup` or `pip install -r requirements.txt`


== Development
Before each commit check source code with `make check` command.

WARNING: If there are some errors fix them!


== License
See the link:./LICENSE.adoc[LICENSE] file for license rights and limitations (MIT).


== TODO

- [ ] Add option to pass parameters to script (interfaces to monitor, json file location,
update rate)

- [ ] Add option to display network usage only/also to terminal (not into `.json` file)

- [ ] Add help message

- [x] Document code

- [x] Add code checking
