= Monitor Network Usage
:toc:
:sectnums:
:sectnumlevels: 4

Monitor current network usage.


== Usage
Run `networkUsageProc.py` and network usage monitoring is started.

Data is stored in json file (currently to `./logs/networkUsage.json` - relative
to `networkUsageProc.py` location)

[source,json]
----
[
  {"name": "enp3s0", "bypsRx": 0, "bypsTx": 0},
  {"name": "wlp4s0", "bypsRx": 51152, "bypsTx": 3183824},
  {"name": "total", "bypsRx": 51152, "bypsTx": 3183824}
]
----

Interfaces monitored are all that match this parameters:

- `wl*`
- `enp*`
- `eth?:`


== Dependencies
* Python (tested with `Python 3.9.5`)


== Development
Before each commit check source code with `make check` command.

WARNING: If there are some errors fix them before committing!

=== Dependencies
* https://www.gnu.org/software/make/[GNU - make]
* `pip` link:requirements.dev.txt[requirements.dev.txt]


== License
See the link:./LICENSE.adoc[LICENSE] file for license rights and limitations (MIT).


== TODO

- [ ] Add option to pass parameters to script (interfaces to monitor, json file location,
update rate)

- [ ] Add option to display network usage only/also to terminal (not into `.json` file)

- [ ] Add help message

- [x] Document code

- [x] Add code checking
